
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Feb 09 08:48:33 CET 2018
//----------------------------------------------------

package yal.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int IDF = 24;
  public static final int EGAL = 19;
  public static final int OU = 17;
  public static final int AFFECT = 25;
  public static final int PLUS = 6;
  public static final int SUP = 12;
  public static final int ECRIRE = 26;
  public static final int NON = 18;
  public static final int MOINS = 7;
  public static final int INF = 13;
  public static final int POINTVIRGULE = 5;
  public static final int PARFER = 11;
  public static final int TYPE = 20;
  public static final int EOF = 0;
  public static final int MULT = 8;
  public static final int EGALEGAL = 14;
  public static final int DIV = 9;
  public static final int CONSTANTEBOOL = 23;
  public static final int ET = 16;
  public static final int error = 1;
  public static final int SYM_PROG = 2;
  public static final int PAROUV = 10;
  public static final int CONSTANTECHAINE = 21;
  public static final int DIFF = 15;
  public static final int CONSTANTEINT = 22;
  public static final int DEBUT = 3;
  public static final int FIN = 4;
}

