
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Apr 08 16:19:30 CEST 2018
//----------------------------------------------------

package yal.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int FONCTION = 5;
  public static final int TANTQUE = 31;
  public static final int CONSTANTECHAINE = 38;
  public static final int MULT = 12;
  public static final int EGAL = 26;
  public static final int REPETER = 32;
  public static final int SI = 27;
  public static final int VIRGULE = 8;
  public static final int FIN = 4;
  public static final int LONGUEUR = 25;
  public static final int SYM_PROG = 2;
  public static final int OU = 23;
  public static final int TYPE = 36;
  public static final int INF = 19;
  public static final int NON = 24;
  public static final int PAROUV = 14;
  public static final int DIV = 13;
  public static final int EGALEGAL = 20;
  public static final int SYM_ECRIRE = 34;
  public static final int PLUS = 10;
  public static final int DEBUT = 3;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int SYM_RETOURNE = 6;
  public static final int MOINS = 11;
  public static final int ET = 22;
  public static final int IDF = 37;
  public static final int SINON = 29;
  public static final int ALORS = 28;
  public static final int CROCHOUV = 16;
  public static final int PARFER = 15;
  public static final int CONSTANTEINT = 39;
  public static final int SYM_LIRE = 35;
  public static final int CONSTANTEBOOL = 40;
  public static final int POINT = 9;
  public static final int POINTVIRGULE = 7;
  public static final int FINTANTQUE = 33;
  public static final int SUP = 18;
  public static final int DIFF = 21;
  public static final int FINSI = 30;
  public static final int CROCHFER = 17;
}

