
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 13 23:13:00 CET 2018
//----------------------------------------------------

package yal.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int FONCTION = 5;
  public static final int TANTQUE = 27;
  public static final int CONSTANTECHAINE = 34;
  public static final int MULT = 11;
  public static final int EGAL = 22;
  public static final int REPETER = 28;
  public static final int SI = 23;
  public static final int VIRGULE = 8;
  public static final int FIN = 4;
  public static final int SYM_PROG = 2;
  public static final int OU = 20;
  public static final int TYPE = 32;
  public static final int INF = 16;
  public static final int NON = 21;
  public static final int PAROUV = 13;
  public static final int DIV = 12;
  public static final int EGALEGAL = 17;
  public static final int SYM_ECRIRE = 30;
  public static final int PLUS = 9;
  public static final int DEBUT = 3;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int SYM_RETOURNE = 6;
  public static final int MOINS = 10;
  public static final int ET = 19;
  public static final int SINON = 25;
  public static final int IDF = 33;
  public static final int ALORS = 24;
  public static final int PARFER = 14;
  public static final int CONSTANTEINT = 35;
  public static final int SYM_LIRE = 31;
  public static final int CONSTANTEBOOL = 36;
  public static final int POINTVIRGULE = 7;
  public static final int FINTANTQUE = 29;
  public static final int SUP = 15;
  public static final int DIFF = 18;
  public static final int FINSI = 26;
}

